name: Deploy
on:
  push:
    tags:
      - dev/[1-9]+.[0-9]+.[0-9]+
      - release/[1-9]+.[0-9]+.[0-9]+
jobs:
  define:
    name: Define environment for deploy
    runs-on: ubuntu-latest

    env:
      IMAGE: ai_hack
      IMAGE_TEST: ai_hack_test

    outputs:
      image: ${{ steps.define_env.outputs.image }}
      service: ${{ steps.define_env.outputs.service }}

    steps:
      - name: Extract branch name
        shell: bash
        run: |
          if [[ "${GITHUB_REF#refs/tags/}" == *release* ]]; then
            echo "branch=master" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          fi
        id: extract_branch

      - name: Define environment
        shell: bash
        run: |
          if [ "${{ steps.extract_branch.outputs.branch }}" = "master" ] ;then depimage=$IMAGE; srvName=$SERVICE_NAME; else depimage=$IMAGE_TEST;srvName=$TEST_SERVICE_NAME ; fi
          echo "image=$depimage" >> $GITHUB_OUTPUT
          echo "service=$srvName" >> $GITHUB_OUTPUT
        id: define_env

  dockerSetup:
    name: Setup and build docker
    runs-on: ubuntu-latest
    needs: define

    env:
      OWNER: mrbelka12000

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo ${{ secrets.PASSWORD }} | docker login ghcr.io -u $OWNER  --password-stdin 

      - name: Docker build
        run: |
          docker build  -f build/Dockerfile -t ghcr.io/$OWNER/${{ needs.define.outputs.image }}:latest .

      - name: Docker push
        run: |
          docker push ghcr.io/$OWNER/${{ needs.define.outputs.image }}:latest
